// Shared query-function generator for async DatabaseClient-style TS drivers
// (pg, bun-sql). Emits `export async function foo(client, params)` bodies
// that call `client.queryOne`, `client.query`, or `client.execute`.
//
// Drivers that don't fit this shape (mysql2 with $1→? placeholder rewrite,
// better-sqlite3 with sync `db.prepare(...).get(...)` calls) do NOT use
// this helper — they have their own body renderers.

use std::collections::BTreeMap;
use std::path::Path;

use crate::error::Result;
use crate::generator::GeneratedFile;
use crate::generator::typescript::common::{
    TsTypeMap, generate_params_type, generate_row_type, json_stringify,
};
use crate::ir::{QueryCommand, QueryDef, SqlcxIR};
use crate::utils::{camel_case, pascal_case};

/// Generate a single async-DatabaseClient-style query function.
pub fn generate_query_function<M: TsTypeMap + ?Sized>(map: &M, query: &QueryDef) -> String {
    let fn_name = camel_case(&query.name);
    let row_type = generate_row_type(map, query);
    let params_interface = generate_params_type(map, query);
    let has_params = !query.params.is_empty();
    let params_type_name = format!("{}Params", pascal_case(&query.name));
    let sql_const = format!(
        "export const {fn_name}Sql = {};",
        json_stringify(&query.sql)
    );

    let params_sig = if has_params {
        format!(", params: {params_type_name}")
    } else {
        String::new()
    };

    let values_arg = if has_params {
        let args: Vec<String> = query
            .params
            .iter()
            .map(|p| format!("params.{}", p.name))
            .collect();
        format!("[{}]", args.join(", "))
    } else {
        "[]".to_string()
    };

    let (return_type, body) = match query.command {
        QueryCommand::One => {
            let type_name = format!("{}Row", pascal_case(&query.name));
            (
                format!("Promise<{type_name} | null>"),
                format!("  return client.queryOne<{type_name}>({fn_name}Sql, {values_arg});"),
            )
        }
        QueryCommand::Many => {
            let type_name = format!("{}Row", pascal_case(&query.name));
            (
                format!("Promise<{type_name}[]>"),
                format!("  return client.query<{type_name}>({fn_name}Sql, {values_arg});"),
            )
        }
        QueryCommand::Exec => (
            "Promise<void>".to_string(),
            format!("  await client.execute({fn_name}Sql, {values_arg});"),
        ),
        QueryCommand::ExecResult => (
            "Promise<{ rowsAffected: number }>".to_string(),
            format!("  return client.execute({fn_name}Sql, {values_arg});"),
        ),
    };

    let mut parts: Vec<String> = Vec::new();
    if !row_type.is_empty() {
        parts.push(row_type);
    }
    if !params_interface.is_empty() {
        parts.push(params_interface);
    }
    parts.push(sql_const);
    parts.push(format!(
        "export async function {fn_name}(client: DatabaseClient{params_sig}): {return_type} {{\n{body}\n}}"
    ));

    parts.join("\n\n")
}

/// Bundle the full queries.ts content for a list of queries.
pub fn generate_query_functions_file<M: TsTypeMap + ?Sized>(
    map: &M,
    queries: &[QueryDef],
) -> String {
    let header = "// Code generated by sqlcx. DO NOT EDIT.\n\nimport type { DatabaseClient } from \"./client\";";
    let functions: Vec<String> = queries
        .iter()
        .map(|q| generate_query_function(map, q))
        .collect();
    if functions.is_empty() {
        return format!("{header}\n");
    }
    format!("{header}\n\n{}", functions.join("\n\n"))
}

/// Generate the full set of files for an async-DatabaseClient driver:
/// client.ts + one *.queries.ts per source file, grouped deterministically.
pub fn generate_driver_files<M: TsTypeMap + ?Sized>(
    map: &M,
    client_ts: String,
    ir: &SqlcxIR,
) -> Result<Vec<GeneratedFile>> {
    let mut files = Vec::new();
    files.push(GeneratedFile {
        path: "client.ts".to_string(),
        content: client_ts,
    });

    let mut grouped: BTreeMap<String, Vec<&QueryDef>> = BTreeMap::new();
    for query in &ir.queries {
        grouped
            .entry(query.source_file.clone())
            .or_default()
            .push(query);
    }
    for (source_file, queries) in &grouped {
        let basename = Path::new(source_file)
            .file_stem()
            .unwrap_or_default()
            .to_string_lossy();
        let owned: Vec<QueryDef> = queries.iter().map(|q| (*q).clone()).collect();
        files.push(GeneratedFile {
            path: format!("{}.queries.ts", basename),
            content: generate_query_functions_file(map, &owned),
        });
    }

    Ok(files)
}
