// database/sql driver generator for Go

use std::collections::BTreeMap;
use std::collections::BTreeSet;
use std::path::Path;

use crate::error::Result;
use crate::generator::{DriverGenerator, GeneratedFile};
use crate::ir::{ColumnDef, QueryCommand, QueryDef, SqlcxIR};
use crate::utils::pascal_case;

use super::structs::{go_base_type, go_column_type, go_imports_for_columns};

pub struct DatabaseSqlGenerator;

// ── Client file ───────────────────────────────────────────────────────────────

fn generate_client() -> String {
    r#"// Code generated by sqlcx. DO NOT EDIT.
package db

import (
	"context"
	"database/sql"
)

type DBTX interface {
	ExecContext(ctx context.Context, query string, args ...interface{}) (sql.Result, error)
	QueryContext(ctx context.Context, query string, args ...interface{}) (*sql.Rows, error)
	QueryRowContext(ctx context.Context, query string, args ...interface{}) *sql.Row
}

type Queries struct {
	db DBTX
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}"#
    .to_string()
}

// ── Query generation ──────────────────────────────────────────────────────────

/// Generate the SQL constant name for a query.
fn sql_const_name(query_name: &str) -> String {
    format!("{}SQL", lcfirst(&pascal_case(query_name)))
}

/// Lowercase the first character of a string.
fn lcfirst(s: &str) -> String {
    let mut c = s.chars();
    match c.next() {
        None => String::new(),
        Some(f) => f.to_lowercase().collect::<String>() + c.as_str(),
    }
}

/// Generate a Go function parameter type from a column.
fn param_go_type(col: &ColumnDef) -> String {
    if col.nullable {
        format!("*{}", go_base_type(&col.sql_type))
    } else {
        go_base_type(&col.sql_type)
    }
}

/// Generate the row struct for queries that return non-table columns.
fn generate_row_struct(query: &QueryDef) -> Option<String> {
    if query.returns.is_empty() {
        return None;
    }
    let type_name = format!("{}Row", pascal_case(&query.name));
    let fields: Vec<String> = query
        .returns
        .iter()
        .map(|col| {
            let field_name = pascal_case(col.alias.as_deref().unwrap_or(&col.name));
            let field_type = go_column_type(col);
            format!(
                "\t{} {} `db:\"{}\" json:\"{}\"`",
                field_name,
                field_type,
                col.alias.as_deref().unwrap_or(&col.name),
                col.alias.as_deref().unwrap_or(&col.name),
            )
        })
        .collect();
    Some(format!(
        "type {} struct {{\n{}\n}}",
        type_name,
        fields.join("\n")
    ))
}

/// Generate a result struct for :execresult queries.
fn generate_result_struct(query: &QueryDef) -> String {
    let type_name = format!("{}Result", pascal_case(&query.name));
    format!(
        "type {} struct {{\n\tRowsAffected int64\n}}",
        type_name
    )
}

/// Generate scan fields (&i.FieldName) for a row.
fn scan_fields(columns: &[ColumnDef]) -> String {
    columns
        .iter()
        .map(|col| {
            let field_name = pascal_case(col.alias.as_deref().unwrap_or(&col.name));
            format!("&i.{}", field_name)
        })
        .collect::<Vec<_>>()
        .join(", ")
}

/// Generate the function signature params for a query.
fn func_params(query: &QueryDef) -> String {
    if query.params.is_empty() {
        return "ctx context.Context".to_string();
    }
    let params: Vec<String> = query
        .params
        .iter()
        .map(|p| {
            let col = ColumnDef {
                name: p.name.clone(),
                alias: None,
                source_table: None,
                sql_type: p.sql_type.clone(),
                nullable: false,
                has_default: false,
            };
            format!("{} {}", p.name, param_go_type(&col))
        })
        .collect();
    format!("ctx context.Context, {}", params.join(", "))
}

/// Generate the args list for ExecContext/QueryContext calls.
fn query_args(query: &QueryDef) -> String {
    if query.params.is_empty() {
        return String::new();
    }
    let args: Vec<String> = query.params.iter().map(|p| p.name.clone()).collect();
    format!(", {}", args.join(", "))
}

/// Generate a full query function.
fn generate_query_function(query: &QueryDef) -> String {
    let const_name = sql_const_name(&query.name);
    let func_name = pascal_case(&query.name);
    let params = func_params(query);
    let args = query_args(query);

    let mut parts: Vec<String> = Vec::new();

    // SQL constant
    parts.push(format!(
        "const {} = \"{}\"",
        const_name,
        query.sql.replace('\\', "\\\\").replace('"', "\\\"").replace('\n', "\\n").replace('\r', "\\r").replace('\t', "\\t"),
    ));

    match query.command {
        QueryCommand::One => {
            let row_type = format!("{}Row", pascal_case(&query.name));
            if let Some(row_struct) = generate_row_struct(query) {
                parts.push(row_struct);
            }
            let scans = scan_fields(&query.returns);
            parts.push(format!(
                "func (q *Queries) {}({}) (*{}, error) {{\n\
                \trow := q.db.QueryRowContext(ctx, {}{})
\tvar i {}
\terr := row.Scan({})
\tif err == sql.ErrNoRows {{
\t\treturn nil, nil
\t}}
\tif err != nil {{
\t\treturn nil, err
\t}}
\treturn &i, nil\n}}",
                func_name, params, row_type, const_name, args,
                row_type, scans,
            ));
        }
        QueryCommand::Many => {
            let row_type = format!("{}Row", pascal_case(&query.name));
            if let Some(row_struct) = generate_row_struct(query) {
                parts.push(row_struct);
            }
            let scans = scan_fields(&query.returns);
            parts.push(format!(
                "func (q *Queries) {}({}) ([]{}, error) {{\n\
                \trows, err := q.db.QueryContext(ctx, {}{})
\tif err != nil {{
\t\treturn nil, err
\t}}
\tdefer rows.Close()
\tvar items []{}
\tfor rows.Next() {{
\t\tvar i {}
\t\tif err := rows.Scan({}); err != nil {{
\t\t\treturn nil, err
\t\t}}
\t\titems = append(items, i)
\t}}
\treturn items, rows.Err()\n}}",
                func_name, params, row_type, const_name, args,
                row_type, row_type, scans,
            ));
        }
        QueryCommand::Exec => {
            parts.push(format!(
                "func (q *Queries) {}({}) error {{\n\
                \t_, err := q.db.ExecContext(ctx, {}{})\n\treturn err\n}}",
                func_name, params, const_name, args,
            ));
        }
        QueryCommand::ExecResult => {
            let result_type = format!("{}Result", pascal_case(&query.name));
            parts.push(generate_result_struct(query));
            parts.push(format!(
                "func (q *Queries) {}({}) (*{}, error) {{\n\
                \tresult, err := q.db.ExecContext(ctx, {}{})
\tif err != nil {{
\t\treturn nil, err
\t}}
\taffected, err := result.RowsAffected()
\tif err != nil {{
\t\treturn nil, err
\t}}
\treturn &{}{{RowsAffected: affected}}, nil\n}}",
                func_name, params, result_type, const_name, args,
                result_type,
            ));
        }
    }

    parts.join("\n\n")
}

/// Collect imports needed for a set of queries.
fn collect_query_imports(queries: &[QueryDef]) -> BTreeSet<String> {
    let mut imports = BTreeSet::new();
    imports.insert("context".to_string());

    let mut needs_database_sql = false;
    for query in queries {
        // Check return columns
        let ret_imports = go_imports_for_columns(&query.returns);
        imports.extend(ret_imports);

        // Check if we need database/sql (for ErrNoRows or Result)
        match query.command {
            QueryCommand::One | QueryCommand::ExecResult => {
                needs_database_sql = true;
            }
            _ => {}
        }

        // Check params for time/json imports
        for param in &query.params {
            let col = ColumnDef {
                name: param.name.clone(),
                alias: None,
                source_table: None,
                sql_type: param.sql_type.clone(),
                nullable: false,
                has_default: false,
            };
            let col_imports = go_imports_for_columns(&[col]);
            imports.extend(col_imports);
        }
    }

    if needs_database_sql {
        imports.insert("database/sql".to_string());
    }

    imports
}

// ── Public API ────────────────────────────────────────────────────────────────

impl DatabaseSqlGenerator {
    pub fn generate_client(&self) -> String {
        generate_client()
    }

    pub fn generate_query_file(&self, queries: &[QueryDef]) -> String {
        let imports = collect_query_imports(queries);
        let imports_str = if imports.is_empty() {
            String::new()
        } else {
            let lines: Vec<String> = imports.iter().map(|i| format!("\t\"{}\"", i)).collect();
            format!("\nimport (\n{}\n)\n", lines.join("\n"))
        };

        let functions: Vec<String> = queries.iter().map(generate_query_function).collect();

        let mut content = String::new();
        content.push_str("// Code generated by sqlcx. DO NOT EDIT.\npackage db\n");
        content.push_str(&imports_str);
        if !functions.is_empty() {
            content.push('\n');
            content.push_str(&functions.join("\n\n"));
            content.push('\n');
        }
        content
    }
}

impl DriverGenerator for DatabaseSqlGenerator {
    fn generate(&self, ir: &SqlcxIR) -> Result<Vec<GeneratedFile>> {
        let mut files = Vec::new();

        // client.go
        files.push(GeneratedFile {
            path: "client.go".to_string(),
            content: self.generate_client(),
        });

        // Group queries by source_file → one .queries.go per file
        let mut grouped: BTreeMap<String, Vec<&QueryDef>> = BTreeMap::new();
        for query in &ir.queries {
            grouped
                .entry(query.source_file.clone())
                .or_default()
                .push(query);
        }
        for (source_file, queries) in &grouped {
            let basename = Path::new(source_file)
                .file_stem()
                .unwrap_or_default()
                .to_string_lossy();
            let owned: Vec<QueryDef> = queries.iter().map(|q| (*q).clone()).collect();
            files.push(GeneratedFile {
                path: format!("{}.queries.go", basename),
                content: self.generate_query_file(&owned),
            });
        }

        Ok(files)
    }
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::parser::postgres::PostgresParser;
    use crate::parser::DatabaseParser;

    fn parse_fixture_ir() -> SqlcxIR {
        let schema_sql = include_str!("../../../../../tests/fixtures/schema.sql");
        let queries_sql = include_str!("../../../../../tests/fixtures/queries/users.sql");
        let parser = PostgresParser::new();
        let (tables, enums) = parser.parse_schema(schema_sql).unwrap();
        let queries = parser
            .parse_queries(queries_sql, &tables, &enums, "queries/users.sql")
            .unwrap();
        SqlcxIR {
            tables,
            queries,
            enums,
        }
    }

    #[test]
    fn generates_client_file() {
        let gen = DatabaseSqlGenerator;
        let content = gen.generate_client();
        assert!(content.contains("type DBTX interface"));
        assert!(content.contains("type Queries struct"));
        assert!(content.contains("func New(db DBTX) *Queries"));
        insta::assert_snapshot!("go_database_sql_client", content);
    }

    #[test]
    fn generates_query_file() {
        let ir = parse_fixture_ir();
        let gen = DatabaseSqlGenerator;
        let content = gen.generate_query_file(&ir.queries);
        assert!(content.contains("func (q *Queries) GetUser"));
        assert!(content.contains("func (q *Queries) ListUsers"));
        assert!(content.contains("func (q *Queries) CreateUser"));
        assert!(content.contains("func (q *Queries) DeleteUser"));
        insta::assert_snapshot!("go_database_sql_queries", content);
    }
}
