import type { SqlcxIR, TableDef, QueryDef, EnumDef } from "@/ir";

export interface LanguageOptions {
  out: string;
  overrides?: Record<string, string>;
}

export interface GeneratedFile {
  path: string;
  content: string;
}

export interface SchemaGenerator {
  name: string;
  generateImports(): string;
  generateEnumSchema(enumDef: EnumDef): string;
  generateSelectSchema(table: TableDef, ir: SqlcxIR): string;
  generateInsertSchema(table: TableDef, ir: SqlcxIR): string;
  generateTypeAlias(name: string, schemaVarName: string): string;
}

export interface DriverGenerator {
  name: string;
  generateImports(): string;
  generateClientAdapter(): string;
  generateQueryFunction(query: QueryDef): string;
}

// DatabaseClient interface is generated by the LanguagePlugin (not the DriverGenerator).
// This prevents collisions when multiple drivers target the same output dir.

export interface LanguagePlugin {
  language: string;
  fileExtension: string;
  generate(ir: SqlcxIR, options: LanguageOptions): GeneratedFile[];
}
